---
- name: Allow release info change
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/99releaseinfochange
    state: present
    create: true
    line: Acquire::AllowReleaseInfoChange::Suite "true";
    mode: 0644

- name: Allow release-info to change for APT repositories
  ansible.builtin.command: apt-get update -y --allow-releaseinfo-change
  changed_when: false

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
